[alt_clients]
user1.domain.controller.address
user2.domain.controller.address
user3.domain.controller.address

[alt_clients:vars]
ansible_user=localadmin
ansible_become=true
ansible_become_method=sudo
ad_domain=domain.controller.address
test_user=